kafka.bootstrap-server=localhost:9092
kafka.topic.string=meu-novo-topico
kafka.topic.dto=sensor-veiculo

kafka.client-id=kafka-consumer-api
kafka.group-id=grupo1

server.port=8080


spring.data.mongodb.database=veiculoprodutorconsumidor
spring.data.mongodb.uri=mongodb://root:root@localhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false


